Admin can mark off a volunteer
jiak1/Vollie-WiEIT-Aut22 pull request #6
Opened 2023-04-09 12:42 UTC by 13204767

Administrators can mark off volunteers.

2023-04-16 02:16 UTC, jiak1 approved these changes

2023-04-16 02:16 UTC, jiak1 requested changes

2023-04-16 02:16 UTC, jiak1 commented on frontend/src/components/attendanceList.tsx
> +        console.log(attendanceList);
I don't think we need this console.log

2023-04-16 02:17 UTC, jiak1 requested changes

2023-04-16 02:17 UTC, jiak1 commented on backend/src/User/user.controller.ts
> +        console.log(userObj);
I don't think we need this console.log

2023-04-29 06:38 UTC, 13204767 reviewed
Removed console logs

2023-04-30 03:20 UTC, jiak1 approved these changes

2023-05-07 06:06 UTC, jiak1 commented
@13204767 is this right to be merged?

2023-05-07 06:16 UTC, 13204767 commented
Yeah my bad

2023-05-07 06:16 UTC, merged